#!/usr/bin/env bash
set -ex

docker run -d --name piranha-api \
  -v /requests-data \
  -e INPUT_DIR=/requests-data/input \
  -e OUTPUT_DIR=/requests-data/output \
  -p 8000:8000  \
  piranhaNET/piranha-api-dev