name: Piranha Electron
on:
  push:
    branches: [ main, mrc-6899-installers ]
  pull_request:
    paths:
      - 'piranha-electron/**'
      - './github/workflows/**'

defaults:
  run:
    working-directory: ./piranha-electron

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 25
          cache: npm
          cache-dependency-path: piranha-electron/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run format:check
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 25
          cache: npm
          cache-dependency-path: piranha-electron/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Unit and integration test
        run: npm run coverage
      - name: E2e test
        run: npm run test:e2e
      # TODO: add this when codecov token is available
      #- name: Upload coverage
      #  uses: codecov/codecov-action@v5
      #  with:
      #    fail_ci_if_error: true
      #    files: ./coverage/coverage-final.json
      #    token: ${{ secrets.CODECOV_TOKEN }}
  electron-build-installers:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 25
          cache: npm
          cache-dependency-path: piranha-electron/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Build/release Electron app
        uses: sudovijay/action-electron-builder@v1.7.4
        with:
          package_root: './piranha-electron'
          skip_build: true
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}